# Generated by Django 3.1.5 on 2021-03-11 12:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Название')),
                ('answer', models.FileField(upload_to='answers/% Y/% m/% d/', verbose_name='Ответ')),
                ('date_present', models.DateField(default=django.utils.timezone.now, verbose_name='Дата отправки')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
        migrations.CreateModel(
            name='Appraisal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Оценка')),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('task', models.FileField(upload_to='tasks/% Y/% m/% d/', verbose_name='Задание')),
                ('date_start', models.DateField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('date_end', models.DateField(default=django.utils.timezone.now, verbose_name='Дата окончания')),
                ('active', models.BooleanField(default=True, verbose_name='Открыто')),
                ('date_opening', models.DateField(blank=True, null=True, verbose_name='Дата открытия')),
                ('num_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.numgroup', verbose_name='Номер группы')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.subject', verbose_name='Предмет')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
            },
        ),
        migrations.CreateModel(
            name='TaskStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=False, verbose_name='Сделано')),
                ('answer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.answer', verbose_name='Ответ')),
                ('appraisal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.appraisal', verbose_name='Оценка')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.student', verbose_name='Студент')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Студент-Задание',
                'verbose_name_plural': 'Студент-Задания',
            },
        ),
    ]
