# Generated by Django 3.1.5 on 2021-03-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.FileField(upload_to='answers/%Y/%m/%d/', verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.FileField(upload_to='tasks/%Y/%m/%d/', verbose_name='Задание'),
        ),
    ]
